//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovative.VehicleRepair.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innovative.VehicleRepair.Application.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist application (Y or N): .
        ///.
        /// </summary>
        public static string ExistAppInputMessage {
            get {
                return ResourceManager.GetString("ExistAppInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please enter one of the following: {0}.
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is large order (Y or N): .
        ///.
        /// </summary>
        public static string LargeOrderInputMessage {
            get {
                return ResourceManager.GetString("LargeOrderInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is new customer (Y or N): .
        ///.
        /// </summary>
        public static string NewCustomerInputMessage {
            get {
                return ResourceManager.GetString("NewCustomerInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status : {0}.
        /// </summary>
        public static string OrderStatusMessage {
            get {
                return ResourceManager.GetString("OrderStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type ( R,H or N): 
        ///Key:        { &apos;R&apos;, OrderType.Repair },
        ///            { &apos;H&apos;, OrderType.Hire },
        ///            { &apos;A&apos;, OrderType.All }, 
        ///            { &apos;r&apos;, OrderType.Repair },
        ///            { &apos;h&apos;, OrderType.Hire },
        ///            { &apos;a&apos;, OrderType.All }
        ///.
        /// </summary>
        public static string OrderTypeInputMessage {
            get {
                return ResourceManager.GetString("OrderTypeInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is rush order (Y or N): .
        ///.
        /// </summary>
        public static string RushOrderInputMessage {
            get {
                return ResourceManager.GetString("RushOrderInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Vehicle service centre
        ///
        ///
        ///.
        /// </summary>
        public static string WellcomeMessage {
            get {
                return ResourceManager.GetString("WellcomeMessage", resourceCulture);
            }
        }
    }
}
